# Generated by Django 3.0.2 on 2020-01-29 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0002_dimension_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
