# Generated by Django 3.0.2 on 2020-01-29 09:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("clusters", "0003_score_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="date",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2020, 1, 29, 9, 59, 58, 10855, tzinfo=utc),
            ),
        ),
    ]
