# Generated by Django 3.0.2 on 2020-01-29 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clusters", "0008_auto_20200129_1136"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score", name="date", field=models.DateTimeField(),
        ),
    ]
