# Generated by Django 3.0.2 on 2020-01-29 10:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clusters', '0009_auto_20200129_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 29, 10, 45, 19, 868734, tzinfo=utc)),
        ),
    ]
