name: CI

on: [push]

jobs:
  build:
    runs-on: [ubuntu-18.04]
    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_USER: ${{ secrets.DJ_DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DJ_DB_PSW }}
          POSTGRES_DB: ${{ secrets.DJ_DB_NAME }}
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Install Requirements
      run: |
        pip install pipenv
        pipenv install
    - name: Update Migrations
      run: |
        pipenv run python3 manage.py makemigrations
        pipenv run python3 manage.py migrate
    - name: Run Test
      run: |
        pipenv run python3 manage.py test  
